source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'  # 统一设置为 iOS 12.0:ml-citation{ref="4,7" data="citationList"}
use_frameworks!
target 'BilisPera' do
  pod 'MJRefresh', '~> 3.7.9'
  pod 'Masonry','~> 1.1.0'
  pod 'SDWebImage'
  pod 'AFNetwork'
  pod 'FBSDKCoreKit'
  pod 'MJExtension'
  pod 'DeviceKit'
  pod 'MBProgressHUD','~> 1.2.0'
  pod 'SDCycleScrollView'
  pod 'IQKeyboardManager'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'  # 强制所有库目标版本:ml-citation{ref="5,7" data="citationList"}
      end
    end
  end
end

